project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex1/In-class_Ex1.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex2/In-class_Ex2.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex3/In-class_Ex3.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex4/In-class_Ex4.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex5/In-class_Ex5.html"
        - text: "In-class Exercise 6"
          href: "In-class_Ex/In-class_Ex6/In-class_Ex6.html"
        - text: "In-class Exercise 7"
          href: "In-class_Ex/In-class_Ex7/In-class_Ex7.html"
        - text: "In-class Exercise 9"
          href: "In-class_Ex/In-class_Ex9/In-class_Ex9.html"
        - text: "In-class Exercise 10"
          href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
        - text: "In-class Exercise 11"
          href: "In-class_Ex/In-class_Ex11/In-class_Ex11.html"
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 11"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex11.html"
        - text: "Hands-on Exercise 12"
          href: "Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex12.html"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1 - Part 1"
          href: "Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html"
        - text: "Take-home Exercise 1 - Part 2"
          href: "Take-home_Ex/Take-home_Ex1/Take-home_Ex1_Part2.html"
        - text: "Take-home Exercise 2 - Part 1"
          href: "Take-home_Ex/Take-home_Ex2/Take-home_Ex02.html"
        - text: "Take-home Exercise 2 - Part 2"
          href: "Take-home_Ex/Take-home_Ex2/Take-home_Ex02_Part2.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html"
    right: 
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

