<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Foo Jia Yi Samantha">
<meta name="dcterms.date" content="2024-10-06">

<title>IS415-GAA - Take-home Exercise 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex1/In-class_Ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex2/In-class_Ex2.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex3/In-class_Ex3.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex4/In-class_Ex4.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex5/In-class_Ex5.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex6/In-class_Ex6.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex7/In-class_Ex7.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex9/In-class_Ex9.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9.html">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html">
 <span class="dropdown-text">Hands-on Exercise 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html">
 <span class="dropdown-text">Hands-on Exercise 11</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html">
 <span class="dropdown-text">Take-home Exercise 1 - Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/Take-home_Ex1_Part2.html">
 <span class="dropdown-text">Take-home Exercise 1 - Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setting-the-scene-drug-abuse-in-thailand" id="toc-setting-the-scene-drug-abuse-in-thailand" class="nav-link active" data-scroll-target="#setting-the-scene-drug-abuse-in-thailand"><strong>1. Setting the Scene: Drug Abuse in Thailand</strong></a></li>
  <li><a href="#methods-used" id="toc-methods-used" class="nav-link" data-scroll-target="#methods-used"><strong>2. Methods Used</strong></a>
  <ul>
  <li><a href="#spatial-autocorrelation" id="toc-spatial-autocorrelation" class="nav-link" data-scroll-target="#spatial-autocorrelation"><strong>2.1 Spatial Autocorrelation</strong></a></li>
  <li><a href="#cluster-and-outlier-analysis" id="toc-cluster-and-outlier-analysis" class="nav-link" data-scroll-target="#cluster-and-outlier-analysis"><strong>2.2 Cluster and Outlier Analysis</strong></a>
  <ul>
  <li><a href="#local-morans-i-and-local-gearys-c" id="toc-local-morans-i-and-local-gearys-c" class="nav-link" data-scroll-target="#local-morans-i-and-local-gearys-c"><strong>2.2.1 Local Moran’s I and Local Geary’s C</strong></a></li>
  <li><a href="#moran-scatterplot" id="toc-moran-scatterplot" class="nav-link" data-scroll-target="#moran-scatterplot"><strong>2.22. Moran Scatterplot</strong></a></li>
  <li><a href="#lisa-cluster-map" id="toc-lisa-cluster-map" class="nav-link" data-scroll-target="#lisa-cluster-map"><strong>2.2.3. LISA Cluster Map</strong></a></li>
  </ul></li>
  <li><a href="#emerging-hot-spot-analysis" id="toc-emerging-hot-spot-analysis" class="nav-link" data-scroll-target="#emerging-hot-spot-analysis"><strong>2.3 Emerging Hot Spot Analysis</strong></a></li>
  </ul></li>
  <li><a href="#importing-packages-into-r" id="toc-importing-packages-into-r" class="nav-link" data-scroll-target="#importing-packages-into-r"><strong>3. Importing Packages into R</strong></a></li>
  <li><a href="#importing-datasets-into-r" id="toc-importing-datasets-into-r" class="nav-link" data-scroll-target="#importing-datasets-into-r"><strong>4. Importing Datasets into R</strong></a>
  <ul>
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data"><strong>4.1 Importing Geospatial Data</strong></a></li>
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data"><strong>4.2 Importing Aspatial Data</strong></a></li>
  <li><a href="#performing-a-join-on-geometry-column" id="toc-performing-a-join-on-geometry-column" class="nav-link" data-scroll-target="#performing-a-join-on-geometry-column"><strong>4.3 Performing a Join on Geometry Column</strong></a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><strong>5. Data Wrangling</strong></a>
  <ul>
  <li><a href="#reduce-data-size" id="toc-reduce-data-size" class="nav-link" data-scroll-target="#reduce-data-size"><strong>5.1 Reduce Data Size</strong></a></li>
  <li><a href="#fixing-missing-values" id="toc-fixing-missing-values" class="nav-link" data-scroll-target="#fixing-missing-values">5.2 Fixing Missing Values</a>
  <ul>
  <li><a href="#identify-missing-values" id="toc-identify-missing-values" class="nav-link" data-scroll-target="#identify-missing-values">5.2.1 Identify Missing Values</a></li>
  <li><a href="#fix-missing-values-discovered" id="toc-fix-missing-values-discovered" class="nav-link" data-scroll-target="#fix-missing-values-discovered">5.2.2 Fix Missing Values Discovered</a></li>
  </ul></li>
  <li><a href="#create-new-total_cases-column" id="toc-create-new-total_cases-column" class="nav-link" data-scroll-target="#create-new-total_cases-column">5.3 Create New <code>total_cases</code> Column</a></li>
  </ul></li>
  <li><a href="#exploratory-geospatial-data-analysis" id="toc-exploratory-geospatial-data-analysis" class="nav-link" data-scroll-target="#exploratory-geospatial-data-analysis">6. Exploratory Geospatial Data Analysis</a>
  <ul>
  <li><a href="#overall-histogram-of-drug-cases" id="toc-overall-histogram-of-drug-cases" class="nav-link" data-scroll-target="#overall-histogram-of-drug-cases">6.1 Overall Histogram of Drug Cases</a></li>
  <li><a href="#histogram-of-drug-cases-by-year" id="toc-histogram-of-drug-cases-by-year" class="nav-link" data-scroll-target="#histogram-of-drug-cases-by-year">6.2 Histogram of Drug Cases by Year</a></li>
  <li><a href="#overall-plot-of-drug-cases" id="toc-overall-plot-of-drug-cases" class="nav-link" data-scroll-target="#overall-plot-of-drug-cases">6.3 Overall Plot of Drug Cases</a></li>
  <li><a href="#plot-of-drug-cases-by-year" id="toc-plot-of-drug-cases-by-year" class="nav-link" data-scroll-target="#plot-of-drug-cases-by-year">6.4 Plot of Drug Cases by Year</a></li>
  </ul></li>
  <li><a href="#global-measures-of-spatial-autocorrelation" id="toc-global-measures-of-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-measures-of-spatial-autocorrelation">7. Global Measures of Spatial Autocorrelation</a>
  <ul>
  <li><a href="#methods-used-1" id="toc-methods-used-1" class="nav-link" data-scroll-target="#methods-used-1">7.1 Methods Used</a></li>
  <li><a href="#computing-contiguity-neighbours" id="toc-computing-contiguity-neighbours" class="nav-link" data-scroll-target="#computing-contiguity-neighbours">7.2 Computing Contiguity Neighbours</a></li>
  <li><a href="#computing-row-standardised-weight-matrix" id="toc-computing-row-standardised-weight-matrix" class="nav-link" data-scroll-target="#computing-row-standardised-weight-matrix">7.3 <strong>Computing Row-Standardised Weight Matrix</strong></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2</h1>
<p class="subtitle lead">Harnessing Geospatial Methods to Analyse Drug Abuse Patterns in Thailand</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Foo Jia Yi Samantha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 6, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 6, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="setting-the-scene-drug-abuse-in-thailand" class="level2">
<h2 class="anchored" data-anchor-id="setting-the-scene-drug-abuse-in-thailand"><strong>1. Setting the Scene: Drug Abuse in Thailand</strong></h2>
<p>In 2022, <strong>567,609 drug users in ASEAN</strong> were treated, in which Thailand was found to have the <strong>highest number of drug users requiring treatment</strong> among ASEAN countries, followed by Malaysia, Indonesia, Laos, the Philippines, and Singapore. (Kahanto M., et al, 2022) Drug abuse is a significant social issue in Thailand, with profound health, financial, and societal implications. Positioned near the Golden Triangle—one of the largest drug production areas in Asia—Thailand faces ongoing challenges due to its geographical proximity and extensive transportation routes, which facilitate drug trafficking. Within Thailand, drug abuse is particularly <strong>prevalent among the youth</strong>, with approximately <strong>2.7 million young people involved</strong>. Of those aged 15–19, around <strong>300,000 are in need of drug treatment</strong>, and vocational students are disproportionately affected compared to their peers in secondary school.</p>
<p>This underscores the importance of drug treatment in addressing the complex problem of substance abuse and reduces the societal costs associated with drug abuse, such as healthcare expenses, lost productivity, and crime. Hence, to better allocate resources and develop targeted interventions, it is <strong>crucial to understand where drug abuse is most concentrated and how it spreads geographically.</strong> This is where geospatial analysis becomes essential.&nbsp;</p>
<p>In this exercise, I will utilise geospatial analysis methods to explore the province-level dynamics of drug abuse in Thailand. This will involve preparing a study area layer as <code>sf</code> polygon features at the province level, including Bangkok, and creating a drug abuse indicators layer within this study area. Using these extracted data layers, I will conduct <strong>global spatial autocorrelation analysis</strong> using <code>sfdep</code> methods, followed by <strong>local spatial autocorrelation analysis.</strong> Finally, I will describe the spatial patterns revealed by determining whether key indicators are spatially dependent, and identifying trends of clusters, outliers and hotspots over time.</p>
</section>
<section id="methods-used" class="level2">
<h2 class="anchored" data-anchor-id="methods-used"><strong>2. Methods Used</strong></h2>
<section id="spatial-autocorrelation" class="level3">
<h3 class="anchored" data-anchor-id="spatial-autocorrelation"><strong>2.1 Spatial Autocorrelation</strong></h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-1506008753.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>This quote from Tobler (1970) highlights the essence of spatial autocorrelation, emphasising the importance of studying how values of the same variable are interconnected across space. By examining spatial dependence, we can better understand local and global patterns and variations. This law suggests that phenomena that are geographically close to each other are more likely to be similar or have some kind of spatial relationship compared to phenomena that are farther apart.&nbsp;</p>
<p>It is also important to note that spatial structure and spatial autocorrelation are inherently interconnected (Tiefelsdorf, 1998):</p>
<ul>
<li><p><strong>Spatial structure</strong> encompasses all the connections through which the autocorrelated phenomenon spreads.</p></li>
<li><p>Without a significant autocorrelated process, spatial structure <strong>cannot be empirically observed.</strong></p></li>
</ul>
<p>Thus, the observed spatial distribution is regarded as a reflection of the underlying spatial process. When spatial autocorrelation is present, the value of a variable at a given observation is connected to the values of that same variable at neighbouring observations:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-3880014486.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500"></p>
</figure>
</div>
<p>Configuration of areas showing different types of autocorrelation (Nguyen K. et al., 2022)</p>
<ul>
<li><p><strong>Positive Spatial Autocorrelation</strong> occurs when similar values of the variable cluster geographically.</p></li>
<li><p><strong>Negative Spatial Autocorrelation</strong> arises when dissimilar values are geographically close, indicating that nearby locations tend to differ more than those that are farther apart. This situation often reflects spatial competition.</p></li>
<li><p>In the <strong>absence of spatial autocorrelation</strong>, the distribution of observations can be considered random.</p></li>
</ul>
</section>
<section id="cluster-and-outlier-analysis" class="level3">
<h3 class="anchored" data-anchor-id="cluster-and-outlier-analysis"><strong>2.2 Cluster and Outlier Analysis</strong></h3>
<p>Cluster and Outlier Analysis can be effectively applied using Local Moran’s I, Local Geary’s C, Moran scatterplots, and LISA Cluster Maps to identify and understand spatial patterns in data. Here’s how each of these methods can be utilised</p>
<section id="local-morans-i-and-local-gearys-c" class="level4">
<h4 class="anchored" data-anchor-id="local-morans-i-and-local-gearys-c"><strong>2.2.1 Local Moran’s I and Local Geary’s C</strong></h4>
<ul>
<li><p><strong>Local Moran’s I</strong>: This statistic assesses local spatial autocorrelation by measuring the degree of similarity of a location’s value to those of its neighbours. It identifies clusters of high or low values (hotspots and cold spots) and outliers (areas where a value is significantly different from its neighbours). By calculating Local Moran’s I for each location, we can highlight areas with significant spatial dependence, helping to identify regions where interventions may be needed.</p></li>
<li><p><strong>Local Geary’s C</strong>: Similar to Local Moran’s I, Local Geary’s C focuses on differences rather than similarities. It quantifies the spatial variation between nearby locations, emphasising dissimilarity. This method can help detect spatial competition, where nearby areas have contrasting values. By using Local Geary’s C, we can uncover regions that may experience conflicting trends or behaviours, providing insights into localised dynamics.</p></li>
</ul>
</section>
<section id="moran-scatterplot" class="level4">
<h4 class="anchored" data-anchor-id="moran-scatterplot"><strong>2.22. Moran Scatterplot</strong></h4>
<ul>
<li><p>The <strong>Moran scatterplot</strong> visualises the relationship between the value of a variable at a location and the average value of its neighbours. We can plot scatterplot to represent a location, with the x-axis showing the local mean of neighbouring values and the y-axis showing the local value.&nbsp;</p></li>
<li><p>Plots like this can help us in identifying clusters (high-high or low-low) and outliers (high-low or low-high). The scatterplot can reveal spatial patterns that are not immediately obvious.</p></li>
</ul>
</section>
<section id="lisa-cluster-map" class="level4">
<h4 class="anchored" data-anchor-id="lisa-cluster-map"><strong>2.2.3. LISA Cluster Map</strong></h4>
<ul>
<li><p>A <strong>LISA Cluster Map</strong> visually represents the results of Local Indicators of Spatial Association, indicating the spatial clusters of similar values (hotspots) and outliers.&nbsp;</p></li>
<li><p>I will use these maps to quickly identify regions of interest such that areas identified as <strong>hotspots will be marked in red</strong> to signify high values surrounded by high values, while <strong>cold spots will be marked in blue</strong> for low values surrounded by low values. Outliers will be highlighted in contrasting colours.</p></li>
</ul>
</section>
</section>
<section id="emerging-hot-spot-analysis" class="level3">
<h3 class="anchored" data-anchor-id="emerging-hot-spot-analysis"><strong>2.3 Emerging Hot Spot Analysis</strong></h3>
<p>There are different methods for analysing spatial patterns and detecting hotspots including spatial autocorrelation and cluster analysis. <strong>Emerging Hot Spot Analysis (EHSA)</strong> is a specific spatio-temporal method used to examine hotspots over a designated <strong>observation period</strong>. It integrates two well-known techniques: the traditional <strong>Getis-Ord Gi* statistic</strong> for hotspot detection and the <strong>Mann-Kendall test</strong> for assessing monotonic trends over time. The main goal of EHSA is to analyse how hot and cold spots change over time, focusing on whether these areas are increasing in intensity, decreasing, or remaining constant.</p>
</section>
</section>
<section id="importing-packages-into-r" class="level2">
<h2 class="anchored" data-anchor-id="importing-packages-into-r"><strong>3. Importing Packages into R</strong></h2>
<p>Let’s load all the required packages for conducting our analysis.</p>
<ul>
<li><a href="https://rdrr.io/github/r-spatial/sf/man/sf-package.html"><code>sf</code></a> : provides a standardised way to encode spatial vector data in R environment, facilitating spatial data operations and analysis.</li>
<li><a href="https://rdrr.io/cran/sf/man/st.html"><code>st</code></a> : create simple features from numeric vectors, matrices, or lists, enabling the representation and manipulation of spatial structures in R.</li>
<li><a href="https://www.tidyverse.org/"><code>tidyverse</code></a> : a collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structure.</li>
<li><a href="https://cran.r-project.org/web/packages/spdep/"><code>sfdep</code></a> : for computing spatial weights, global and local spatial autocorrelation statistics</li>
<li><a href="https://cran.r-project.org/web/packages/tmap/"><code>tmap</code></a> : for creating static and interactive visualisations and maps.</li>
<li><a href="https://cran.r-project.org/web/packages/ggplot2/"><code>ggplot2</code></a> : for creating advanced visualisations, graphics and maps using the Grammar of Graphics.</li>
<li><a href="https://cran.r-project.org/web/packages/spdep/"><code>knitr</code></a> : for dynamic report generation in R using Literate Programming techniques.</li>
<li><a href="https://cran.r-project.org/web/packages/Kendall/"><code>Kendall</code></a> : for computing the Kendall rank correlation and Mann-Kendall trend test</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, st, tidyverse, lubridate, sfdep, tmap, ggplot2, knitr, Kendall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-datasets-into-r" class="level2">
<h2 class="anchored" data-anchor-id="importing-datasets-into-r"><strong>4. Importing Datasets into R</strong></h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-2233382775.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="528"></p>
</figure>
</div>
<p>We will be leveraging two datasets in this exercise. The first dataset to be used is Thailand’s provincial boundary is <code>tha_admbnda_adm1_rtsd_20220121</code> which exists in <strong>ESRI .shp</strong> <strong>format</strong> and is based on the Thailand geographic coordinate system. This dataset is extracted from <a href="https://data.humdata.org/dataset/cod-ab-tha?">Thailand - Subnational Administrative Boundaries</a> via the HDX portal.</p>
<p>The second dataset <code>thai_drug_offenses_2017_2022</code> consists of aspatial data in a <strong>CSV format</strong> that contains reported cases of drug offences in Thailand from 2017 to 2022. The dataset is extracted from <a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-drug-offenses-2017-2022">Thailand Drug Offenses [2017-2022]</a> in Kaggle.</p>
<section id="importing-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-geospatial-data"><strong>4.1 Importing Geospatial Data</strong></h3>
<p>In this section, <code>st_read()</code> of sf package will be used to import <code>tha_admbnda_adm1_rtsd_20220121</code> dataset into the R environment. The <strong><code>st_transform()</code></strong> function below converts the CRS of the <strong><code>sf</code></strong> object to EPSG:32647 which maps to Thailand’s UTM zone, particularly for Western/Central parts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>thai_boundary <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,<span class="at">layer =</span> <span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>) <span class="sc">%&gt;%</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `C:\SamanthaxFoo\IS415-GAA\Take-home_Ex\Take-home_Ex2\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thai_boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 77
Columns: 17
$ Shape_Leng &lt;dbl&gt; 2.417227, 1.695100, 1.251111, 1.884945, 3.041716, 1.739908,…
$ Shape_Area &lt;dbl&gt; 0.13133873, 0.07926199, 0.05323766, 0.12698345, 0.21393797,…
$ ADM1_EN    &lt;chr&gt; "Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "P…
$ ADM1_TH    &lt;chr&gt; "กรุงเทพมหานคร", "สมุทรปราการ", "นนทบุรี", "ปทุมธานี", "พระนครศรีอ…
$ ADM1_PCODE &lt;chr&gt; "TH10", "TH11", "TH12", "TH13", "TH14", "TH15", "TH16", "TH…
$ ADM1_REF   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM0_EN    &lt;chr&gt; "Thailand", "Thailand", "Thailand", "Thailand", "Thailand",…
$ ADM0_TH    &lt;chr&gt; "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศ…
$ ADM0_PCODE &lt;chr&gt; "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH",…
$ date       &lt;date&gt; 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18…
$ validOn    &lt;date&gt; 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22…
$ validTo    &lt;date&gt; -001-11-30, -001-11-30, -001-11-30, -001-11-30, -001-11-30…
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((674339.8 15..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>Let’s verify the coordinate reference systems of the <code>thai_boundary</code> object to ensure the assignment of the correct CRS value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thai_boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32647 
  wkt:
PROJCRS["WGS 84 / UTM zone 47N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 47N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",99,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Navigation and medium accuracy spatial referencing."],
        AREA["Between 96°E and 102°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Indonesia. Laos. Malaysia - West Malaysia. Mongolia. Myanmar (Burma). Russian Federation. Thailand."],
        BBOX[0,96,84,102]],
    ID["EPSG",32647]]</code></pre>
</div>
</div>
<p>Before we delve into further data analysis, it is crucial that we first understand the levels of administration that makes up Thailand today. In particular, Thailand has 4 levels of administration, i.e.&nbsp;<strong>level 0 (country), 1 (province), 2 (district),</strong> and <strong>3 (sub-district) boundaries.</strong> Thailand comprises 76 provinces (known as จังหวัด in Thai or changwat in English), along with one special administrative area, Bangkok, the capital.&nbsp;</p>
<ul>
<li>These provinces function as the main local government units and possess legal personhood.&nbsp;</li>
<li>Each province is subdivided into amphoe (districts), which are further broken down into tambon (sub-districts), representing the next tier of local governance.&nbsp;</li>
<li><strong>For this analysis, I will only focus on the province administration level.</strong></li>
</ul>
<p>We can visualise the structure of our geospatial object as such.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the provinces of Thailand with labels</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(thai_boundary) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>()<span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"Provinces of Thailand"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.show =</span> <span class="cn">FALSE</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">frame =</span> <span class="cn">FALSE</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"ADM1_EN"</span>, <span class="at">size =</span> <span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-2171615491.png" class="img-fluid"></p>
</section>
<section id="importing-aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-aspatial-data"><strong>4.2 Importing Aspatial Data</strong></h3>
<p>In this section, <code>read_csv()</code> of <strong>sf</strong> package will be used to import the csv file into the R environment. The output is a R dataframe class containing 5 unique columns of drug offences in Thailand from 2017 - 2022.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thai_drug_offenses_2017_2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 7392 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): types_of_drug_offenses, province_th, province_en
dbl (2): fiscal_year, no_cases

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(drug_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  fiscal_year types_of_drug_offenses no_cases province_th   province_en         
        &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;               
1        2017 drug_use_cases            11871 กรุงเทพมหานคร  Bangkok             
2        2017 drug_use_cases              200 ชัยนาท         Chai Nat            
3        2017 drug_use_cases              553 นนทบุรี         Nonthaburi          
4        2017 drug_use_cases              450 ปทุมธานี        Pathum Thani        
5        2017 drug_use_cases              378 พระนครศรีอยุธยา Phra Nakhon Si Ayut…
6        2017 drug_use_cases              727 ลพบุรี          Loburi              </code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 54%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Column Name</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Description</strong></td>
</tr>
<tr class="even">
<td>fiscal_year</td>
<td><em>&lt;dbl&gt;</em></td>
<td>The fiscal year during which the drug offenses were recorded.</td>
</tr>
<tr class="odd">
<td>types_of_drug_offenses</td>
<td><em>&lt;chr&gt;</em></td>
<td>The specific type or category of drug offence being reported.</td>
</tr>
<tr class="even">
<td>no_cases</td>
<td><em>&lt;dbl&gt;</em></td>
<td>The total number of cases recorded for the specific combination of fiscal year</td>
</tr>
<tr class="odd">
<td>province_th</td>
<td><em>&lt;chr&gt;</em></td>
<td>The name of the province in Thailand, written in Thai.</td>
</tr>
<tr class="even">
<td>province_en</td>
<td><em>&lt;chr&gt;</em></td>
<td>The name of the province in Thailand, written in English.</td>
</tr>
</tbody>
</table>
</section>
<section id="performing-a-join-on-geometry-column" class="level3">
<h3 class="anchored" data-anchor-id="performing-a-join-on-geometry-column"><strong>4.3 Performing a Join on Geometry Column</strong></h3>
<p>Next, we will want to aggregate the total number of drug use cases according to each 77 provinces in Thailand. Here, I use <code>left_join()</code> to associate each drug use case to its respective province (i.e.&nbsp;the geometry of the drug case).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Count rows before the join</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>initial_row_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(drug_cases)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Perform the join and convert to sf</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(thai_boundary <span class="sc">%&gt;%</span> <span class="fu">select</span>(geometry, ADM1_EN, ADM1_PCODE), </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"province_en"</span> <span class="ot">=</span> <span class="st">"ADM1_EN"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>()</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Count rows after the join</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>final_row_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(drug_cases)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Check if rows were dropped</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (initial_row_count <span class="sc">!=</span> final_row_count) {</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Rows were dropped during the join.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Rows before join:"</span>, initial_row_count, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Rows after join:"</span>, final_row_count, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"No rows were dropped during the join.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>No rows were dropped during the join.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(drug_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,392
Columns: 7
$ fiscal_year            &lt;dbl&gt; 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017,…
$ types_of_drug_offenses &lt;chr&gt; "drug_use_cases", "drug_use_cases", "drug_use_c…
$ no_cases               &lt;dbl&gt; 11871, 200, 553, 450, 378, 727, 820, 69, 127, 2…
$ province_th            &lt;chr&gt; "กรุงเทพมหานคร", "ชัยนาท", "นนทบุรี", "ปทุมธานี", "พร…
$ province_en            &lt;chr&gt; "Bangkok", "Chai Nat", "Nonthaburi", "Pathum Th…
$ ADM1_PCODE             &lt;chr&gt; "TH10", "TH18", "TH12", "TH13", "TH14", NA, "TH…
$ geometry               &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((674339.8 15..., MU…</code></pre>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling"><strong>5. Data Wrangling</strong></h2>
<section id="reduce-data-size" class="level3">
<h3 class="anchored" data-anchor-id="reduce-data-size"><strong>5.1 Reduce Data Size</strong></h3>
<p>To reduce the memory load, we can drop the province names in Thai from our aspatial dataset as it is not relevant for this study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> <span class="fu">subset</span>(drug_cases, <span class="at">select =</span> <span class="fu">c</span>(<span class="sc">-</span>province_th))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(drug_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 5 fields (with 1 geometry empty)
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 577383.3 ymin: 1492136 xmax: 710569.3 ymax: 1704842
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 6 × 6
  fiscal_year types_of_drug_offenses no_cases province_en             ADM1_PCODE
        &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt; &lt;chr&gt;                   &lt;chr&gt;     
1        2017 drug_use_cases            11871 Bangkok                 TH10      
2        2017 drug_use_cases              200 Chai Nat                TH18      
3        2017 drug_use_cases              553 Nonthaburi              TH12      
4        2017 drug_use_cases              450 Pathum Thani            TH13      
5        2017 drug_use_cases              378 Phra Nakhon Si Ayuttha… TH14      
6        2017 drug_use_cases              727 Loburi                  &lt;NA&gt;      
# ℹ 1 more variable: geometry &lt;MULTIPOLYGON [m]&gt;</code></pre>
</div>
</div>
<p>We’ll also only retain columns that are most useful from <code>thai_boundary</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>thai_boundary <span class="ot">&lt;-</span> <span class="fu">subset</span>(thai_boundary, <span class="at">select =</span> <span class="fu">c</span>(Shape_Leng, Shape_Area, ADM1_EN, ADM1_PCODE, geometry))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(thai_boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 628303 ymin: 1490796 xmax: 712440.5 ymax: 1636901
Projected CRS: WGS 84 / UTM zone 47N
  Shape_Leng Shape_Area                  ADM1_EN ADM1_PCODE
1   2.417227 0.13133873                  Bangkok       TH10
2   1.695100 0.07926199             Samut Prakan       TH11
3   1.251111 0.05323766               Nonthaburi       TH12
4   1.884945 0.12698345             Pathum Thani       TH13
5   3.041716 0.21393797 Phra Nakhon Si Ayutthaya       TH14
6   1.739908 0.07920961                Ang Thong       TH15
                        geometry
1 MULTIPOLYGON (((674339.8 15...
2 MULTIPOLYGON (((687139.8 15...
3 MULTIPOLYGON (((644817.9 15...
4 MULTIPOLYGON (((704086 1575...
5 MULTIPOLYGON (((662941.6 16...
6 MULTIPOLYGON (((643472.8 16...</code></pre>
</div>
</div>
</section>
<section id="fixing-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="fixing-missing-values">5.2 Fixing Missing Values</h3>
<p>There are no troublesome rows in the <code>drug_cases</code> dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(thai_boundary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#thai_boundary[!complete.cases(st_drop_geometry(thai_boundary)), ]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(drug_cases))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<section id="identify-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="identify-missing-values">5.2.1 Identify Missing Values</h4>
<p>We can observe <strong><em>192</em></strong> reported offences that do not include the <strong>ADM1_PCODE</strong> as seen from how some rows contain empty values ‘NA’. We are also getting the <strong>192 empty</strong> <code>geometry</code> values as returned from the null test below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(ADM1_PCODE)) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(province_en, ADM1_PCODE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 192 features and 2 fields (with 192 geometries empty)
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 192 × 3
   province_en ADM1_PCODE           geometry
   &lt;chr&gt;       &lt;chr&gt;      &lt;MULTIPOLYGON [m]&gt;
 1 Loburi      &lt;NA&gt;                    EMPTY
 2 buogkan     &lt;NA&gt;                    EMPTY
 3 Loburi      &lt;NA&gt;                    EMPTY
 4 buogkan     &lt;NA&gt;                    EMPTY
 5 Loburi      &lt;NA&gt;                    EMPTY
 6 buogkan     &lt;NA&gt;                    EMPTY
 7 Loburi      &lt;NA&gt;                    EMPTY
 8 buogkan     &lt;NA&gt;                    EMPTY
 9 Loburi      &lt;NA&gt;                    EMPTY
10 buogkan     &lt;NA&gt;                    EMPTY
# ℹ 182 more rows</code></pre>
</div>
</div>
<p>The root cause of this problem lies in how these two province names were incorrectly spelled in the <strong>province_en</strong> column of <code>drug_casses</code> , causing an incomplete <code>left_join()</code> to be executed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(drug_cases[<span class="sc">!</span><span class="fu">complete.cases</span>(<span class="fu">st_drop_geometry</span>(drug_cases)), ][<span class="fu">c</span>(<span class="st">'province_en'</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 1 field (with 2 geometries empty)
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 2 × 2
  province_en           geometry
  &lt;chr&gt;       &lt;MULTIPOLYGON [m]&gt;
1 Loburi                   EMPTY
2 buogkan                  EMPTY</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>thai_boundary <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Lop Buri"</span> <span class="sc">|</span> ADM1_EN <span class="sc">==</span> <span class="st">"Bueng Kan"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM1_PCODE, ADM1_EN) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  ADM1_PCODE ADM1_EN                                                    geometry
  &lt;chr&gt;      &lt;chr&gt;                                            &lt;MULTIPOLYGON [m]&gt;
1 TH16       Lop Buri  (((751293.3 1742960, 751337.4 1742928, 751437.2 1742942,…
2 TH38       Bueng Kan (((965496 2045531, 965625.5 2045528, 965836.6 2045537, 9…</code></pre>
</div>
</div>
</section>
<section id="fix-missing-values-discovered" class="level4">
<h4 class="anchored" data-anchor-id="fix-missing-values-discovered">5.2.2 Fix Missing Values Discovered</h4>
<p>Let’s fix these NA values by transforming the two province names to their correct names.</p>
<ul>
<li><strong>Step 1</strong>: Replace Loburi –&gt; Lop Buri, buogkan –&gt; Bueng Kan</li>
<li><strong>Step 2:</strong> Replace ‘NA’ <code>ADM1_PCDOE</code> with the correct province code - TH16 and TH38 for Lop Buri and Bueng Kan respectively</li>
<li><strong>Step 3:</strong> Replace the existing geometry column in <code>drug_cases</code> with the right geometry</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the geometry for Lop Buri</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>lop_buri_geometry <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">==</span> <span class="st">"Lop Buri"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(<span class="at">first_geometry =</span> <span class="fu">st_union</span>(geometry)) <span class="sc">%&gt;%</span>  </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(first_geometry)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the geometry for Bueng Kan</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>bueng_kan_geometry <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">==</span> <span class="st">"Bueng Kan"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(<span class="at">first_geometry =</span> <span class="fu">st_union</span>(geometry)) <span class="sc">%&gt;%</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(first_geometry)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix incorrect province names</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">province_en =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>      province_en <span class="sc">==</span> <span class="st">"Loburi"</span> <span class="sc">~</span> <span class="st">"Lop Buri"</span>,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>      province_en <span class="sc">==</span> <span class="st">"buogkan"</span> <span class="sc">~</span> <span class="st">"Bueng Kan"</span>,</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> province_en  </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix empty province code</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ADM1_PCODE =</span> <span class="fu">ifelse</span>(province_en <span class="sc">==</span> <span class="st">"Lop Buri"</span> <span class="sc">&amp;</span> </span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">is.na</span>(ADM1_PCODE),<span class="st">"TH16"</span>, </span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(province_en <span class="sc">==</span> <span class="st">"Bueng Kan"</span> <span class="sc">&amp;</span> </span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">is.na</span>(ADM1_PCODE),<span class="st">"TH38"</span>, ADM1_PCODE)))</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix empty geometry</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>thai_boundary_no_geom <span class="ot">&lt;-</span> thai_boundary <span class="sc">%&gt;%</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ADM1_EN, geometry)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(thai_boundary_no_geom, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"province_en"</span> <span class="ot">=</span> <span class="st">"ADM1_EN"</span>)) </span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>drug_cases <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(drug_cases)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have successfully removed all NA values found in <code>drug_cases</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(drug_cases))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the updated drug_cases</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>drug_cases[<span class="sc">!</span><span class="fu">complete.cases</span>(<span class="fu">st_drop_geometry</span>(drug_cases)), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 0 features and 5 fields
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 0 × 6
# ℹ 6 variables: fiscal_year &lt;dbl&gt;, types_of_drug_offenses &lt;chr&gt;,
#   no_cases &lt;dbl&gt;, province_en &lt;chr&gt;, ADM1_PCODE &lt;chr&gt;,
#   geometry &lt;GEOMETRY [m]&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="create-new-total_cases-column" class="level3">
<h3 class="anchored" data-anchor-id="create-new-total_cases-column">5.3 Create New <code>total_cases</code> Column</h3>
<p>Next, I create a new dataframe <code>drug_cases_province</code> to count the total number of cases per province.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>drug_cases_province <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(province_en) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cases =</span> <span class="fu">sum</span>(no_cases), </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ADM1_PCODE =</span> <span class="fu">first</span>(ADM1_PCODE),              </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">geometry =</span> <span class="fu">first</span>(geometry), </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>                           </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>()</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(drug_cases_province)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 77 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 325178.8 ymin: 620860.6 xmax: 1213656 ymax: 2263241
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 77 × 4
   province_en   total_cases ADM1_PCODE                                 geometry
   &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;                            &lt;MULTIPOLYGON [m]&gt;
 1 Amnat Charoen       35435 TH37       (((1137720 1809629, 1137724 1809622, 11…
 2 Ang Thong           16168 TH15       (((643472.8 1636469, 643496 1636423, 64…
 3 Bangkok            286480 TH10       (((674339.8 1543300, 674382.3 1543278, …
 4 Bueng Kan           35287 TH38       (((965496 2045531, 965625.5 2045528, 96…
 5 Buri Ram            57352 TH31       (((921217 1750212, 921217 1750211, 9212…
 6 Chachoengsao        53514 TH24       (((722656.1 1546054, 722796 1546041, 72…
 7 Chai Nat            15310 TH18       (((620165.4 1704256, 620291.4 1704247, …
 8 Chaiyaphum          64497 TH36       (((772997.4 1851276, 773104.5 1851216, …
 9 Chanthaburi         31473 TH22       (((853764.8 1360716, 853783.1 1360713, …
10 Chiang Mai         121812 TH50       (((554883.3 2226795, 555000.6 2226791, …
# ℹ 67 more rows</code></pre>
</div>
</div>
<p>I will also create a new <code>drug_cases_province_year</code> to aggregate the total number of cases for each province and based on each year, regardless of drug offense type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>drug_cases_province_year <span class="ot">&lt;-</span> drug_cases <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(province_en, fiscal_year) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fiscal_year =</span> <span class="fu">first</span>(fiscal_year),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cases =</span> <span class="fu">sum</span>(no_cases), </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ADM1_PCODE =</span> <span class="fu">first</span>(ADM1_PCODE),              </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">geometry =</span> <span class="fu">first</span>(geometry), </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>                           </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>()</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(drug_cases_province_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 462 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 325178.8 ymin: 620860.6 xmax: 1213656 ymax: 2263241
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 462 × 5
   province_en   fiscal_year total_cases ADM1_PCODE                     geometry
   &lt;chr&gt;               &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;                &lt;MULTIPOLYGON [m]&gt;
 1 Amnat Charoen        2017        5076 TH37       (((1137720 1809629, 1137724…
 2 Amnat Charoen        2018        5651 TH37       (((1137720 1809629, 1137724…
 3 Amnat Charoen        2019        7339 TH37       (((1137720 1809629, 1137724…
 4 Amnat Charoen        2020        3949 TH37       (((1137720 1809629, 1137724…
 5 Amnat Charoen        2021        8961 TH37       (((1137720 1809629, 1137724…
 6 Amnat Charoen        2022        4459 TH37       (((1137720 1809629, 1137724…
 7 Ang Thong            2017        1614 TH15       (((643472.8 1636469, 643496…
 8 Ang Thong            2018        2717 TH15       (((643472.8 1636469, 643496…
 9 Ang Thong            2019        2781 TH15       (((643472.8 1636469, 643496…
10 Ang Thong            2020        2636 TH15       (((643472.8 1636469, 643496…
# ℹ 452 more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-geospatial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-geospatial-data-analysis">6. Exploratory Geospatial Data Analysis</h2>
<section id="overall-histogram-of-drug-cases" class="level3">
<h3 class="anchored" data-anchor-id="overall-histogram-of-drug-cases">6.1 Overall Histogram of Drug Cases</h3>
<p>I employed the <code>geom_histogram</code> function of the <code>ggplot</code> package to plot histogram distributions of the spread of the number of drug cases found in Thailand from 2017 to 2022.</p>
<p>Overall, the number of cases appears to be relatively right-skewed with some outliers indicating a significantly high number of drug cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(drug_cases, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Histogram of Total Drug Cases in Thailand (2017-2022)"</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="histogram-of-drug-cases-by-year" class="level3">
<h3 class="anchored" data-anchor-id="histogram-of-drug-cases-by-year">6.2 Histogram of Drug Cases by Year</h3>
<p>Based on each year category, we see that there is a similar pattern of drug cases skewed towards the lower end with an uneven distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram for each year</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>drug_cases_2017 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2017</span>)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>hist_2017 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2017, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2017"</span>) <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>) </span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>drug_cases_2018 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2018</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>hist_2018 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2018, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2018"</span>) <span class="sc">+</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>drug_cases_2019 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2019</span>)</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>hist_2019 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2019, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2019"</span>) <span class="sc">+</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>drug_cases_2020 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>hist_2020 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2020, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2020"</span>) <span class="sc">+</span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>drug_cases_2021 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2021</span>)</span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>hist_2021 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2021, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2021"</span>) <span class="sc">+</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>drug_cases_2022 <span class="ot">&lt;-</span> <span class="fu">filter</span>(drug_cases, fiscal_year <span class="sc">==</span> <span class="dv">2022</span>)</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a>hist_2022 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(drug_cases_2022, <span class="fu">aes</span>(<span class="at">x =</span> no_cases)) <span class="sc">+</span> </span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"skyblue3"</span>) <span class="sc">+</span> </span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of Cases"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Drug Cases in 2022"</span>) <span class="sc">+</span></span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange all histograms in a grid layout</span></span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(hist_2017, hist_2018, hist_2019, hist_2020, hist_2021, hist_2022, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-1227396748.png" class="img-fluid"></p>
</section>
<section id="overall-plot-of-drug-cases" class="level3">
<h3 class="anchored" data-anchor-id="overall-plot-of-drug-cases">6.3 Overall Plot of Drug Cases</h3>
<p>As such, an <strong><em>quantile</em></strong> interval will be more suitable in plotting the total number of cases for each province as shown in the tmap output below. Additionally, we can use the default break of <strong>5</strong> to capture a suitable level of granularity across all provinces. For comparison purposes, I will also plot the <strong><em>equal</em></strong> scale as shown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First plot using quantile interval</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>plot_quantile <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(drug_cases_province) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>, </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Number of Drug Cases"</span>) <span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of Drug Cases in Thailand </span><span class="sc">\n</span><span class="st"> by Province (Quantile Interval)"</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.7</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.fontface =</span> <span class="st">"bold"</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>, </span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Second plot using equal interval</span></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>plot_equal <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(drug_cases_province) <span class="sc">+</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>, </span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"equal"</span>, </span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Number of Drug Cases"</span>) <span class="sc">+</span></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of Drug Cases in Thailand </span><span class="sc">\n</span><span class="st"> by Province (Equal Interval)"</span>,</span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.7</span>,</span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.fontface =</span> <span class="st">"bold"</span>,</span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>, </span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine both plots side by side</span></span>
<span id="cb43-40"><a href="#cb43-40" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(plot_quantile, plot_equal, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-234682238.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Observations">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Overall, we can observe that the highest number of drug cases are found in the <strong>north-western, central, eastern and southern</strong> provinces of Thailand as seen in the darker regions. Namely..</p>
<ul>
<li>North-west: Chiang Mai, Chiang Rai</li>
<li>Central: Chaiyaphum, Khon Kaen and Nakhon-Ratchasima</li>
<li>East: Sisaket, Ubon-Ratchathani</li>
<li>South: Surat Thani, Nakhon Si Thammarat, Phuket</li>
</ul>
<p>It is worth noting that smaller provinces are likely to be lighter in shade due to their smaller geographic area.</p>
</div>
</div>
</section>
<section id="plot-of-drug-cases-by-year" class="level3">
<h3 class="anchored" data-anchor-id="plot-of-drug-cases-by-year">6.4 Plot of Drug Cases by Year</h3>
<p>When we further categorise the drug cases by year, we can see that there is an even spread of cases</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>plot_quantile_year <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(drug_cases_province_year) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>, </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">by=</span><span class="st">"fiscal_year"</span>, <span class="at">free.coords =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of Drug Cases in Thailand </span><span class="sc">\n</span><span class="st"> by Province for Each Year (Quantile Interval)"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.7</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.fontface =</span> <span class="st">"bold"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>, </span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) </span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>plot_quantile_year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-1946072980.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create temporal maps</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>temporal_maps <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(drug_cases_province_year) <span class="sc">+</span>  </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"total_cases"</span>,  </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Blues"</span>,  </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>, </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Drug Cases"</span>) <span class="sc">+</span> </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.title.size =</span> <span class="fl">1.8</span>,</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">along =</span> <span class="st">"fiscal_year"</span>, <span class="at">free.coords =</span> <span class="cn">FALSE</span>)</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate animation</span></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_animation</span>(temporal_maps, <span class="at">filename =</span> <span class="st">"thailand_drugs_temporal.gif"</span>, </span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">delay =</span> <span class="dv">150</span>, <span class="at">width =</span> <span class="dv">1000</span>, <span class="at">height =</span> <span class="dv">1200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Creating frames</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>===========================</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=============</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=============</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>==============</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=============</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Creating animation
Animation saved to C:\SamanthaxFoo\IS415-GAA\Take-home_Ex\Take-home_Ex2\thailand_drugs_temporal.gif </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Include the generated GIF</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"thailand_drugs_temporal.gif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="thailand_drugs_temporal.gif" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="global-measures-of-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-measures-of-spatial-autocorrelation">7. Global Measures of Spatial Autocorrelation</h2>
<section id="methods-used-1" class="level3">
<h3 class="anchored" data-anchor-id="methods-used-1">7.1 Methods Used</h3>
<p>This section delves into analysing the spatial autocorrelation of our drug cases dataset and assessing how the presence of drug abuse in a province may influence and form clusters around it.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-3777711026.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="418"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-550850738.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>&lt;INSERT THE THREE TYPES OF METHODS&gt;</p>
</section>
<section id="computing-contiguity-neighbours" class="level3">
<h3 class="anchored" data-anchor-id="computing-contiguity-neighbours">7.2 Computing Contiguity Neighbours</h3>
<p>I decided to use the Queen criterion in deriving our <strong>neighbour list object</strong>. To do so, we will utilise the <code>st_contiguity()</code> function from the <code>sfdep</code> package to create contiguity weight matrices for the study area. This function generates a list of neighbors based on provinces that <strong>share</strong> <strong>contiguous boundaries.</strong> It is worth noting that the function only supports the rook and queen criteria which is suitable for our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>thailand_nb_q <span class="ot">&lt;-</span> <span class="fu">st_contiguity</span>(drug_cases_province, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(thailand_nb_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 352 
Percentage nonzero weights: 5.93692 
Average number of links: 4.571429 
1 region with no links:
48
2 disjoint connected subgraphs
Link number distribution:

 0  1  2  3  4  5  6  7  8  9 
 1  1  5 17 15 17 10  5  4  2 
1 least connected region:
71 with 1 link
2 most connected regions:
17 69 with 9 links</code></pre>
</div>
</div>
<p>Each number returned above is an ID assigned to each province from the <code>st_contiguity()</code> function. Let’s find out the specific provinces highlighted by the summary above!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>province_ids <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">region_id =</span> <span class="fu">seq_along</span>(drug_cases_province<span class="sc">$</span>province_en),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">province_en =</span> drug_cases_province<span class="sc">$</span>province_en</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>province_ids[province_ids<span class="sc">$</span>region_id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">17</span>, <span class="dv">48</span>, <span class="dv">69</span>, <span class="dv">71</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   region_id province_en
17        17   Khon Kaen
48        48      Phuket
69        69         Tak
71        71        Trat</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Observations">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observations
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>I can observe a total of 77 provinces (regions) in the dataset with <strong>352 neighbouring links</strong> between the provinces</li>
<li>There is <strong>roughly 5.94% non-zero neighbour relationships</strong>. This indicates only a small proportion of total possible connections have neighbours.</li>
<li>On average, we can also observe that <strong>each province</strong> has <strong>4.57 neighbouring regions.</strong></li>
<li><strong>Region</strong> <strong>48</strong> (Phuket province) has <strong>no neighbouring regions</strong></li>
<li><strong>Region 71</strong> (Trat province) is one of the <strong>least connected provinces</strong> with only 1 neighbouring region</li>
<li><strong>Regions 17</strong> (Khon Kaen province) and <strong>69</strong> (Tak province) are the two provinces with the <strong>most neighbours</strong>, each sharing boundaries with 9 other provinces</li>
</ul>
</div>
</div>
</section>
<section id="computing-row-standardised-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="computing-row-standardised-weight-matrix">7.3 <strong>Computing Row-Standardised Weight Matrix</strong></h3>
<p>Next, I attempt to calculate spatial weights but the <strong>isolated region (48)</strong> is causing issues as spatial weights calculations require all regions to have neighbors.</p>
<p>To resolve the issue caused by the isolated region, I will use the <code>allow_zero = TRUE</code> option when calculating spatial weights, which will allow the analysis to proceed despite isolated regions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>thailand_wt <span class="ot">&lt;-</span> <span class="fu">st_weights</span>(thailand_nb_q, <span class="at">style =</span> <span class="st">"W"</span>, <span class="at">allow_zero =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will mutate the newly created neighbour list object&nbsp;<code>thailand_nb_1</code> and weight matrix&nbsp;<code>thailand_wt</code>&nbsp;into our existing&nbsp;<code>drug_cases_province</code>. This results in a newly created object called <code>wm_1</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> drug_cases_province <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> thailand_nb_q,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> thailand_wt,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>wm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 77 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 325178.8 ymin: 620860.6 xmax: 1213656 ymax: 2263241
Projected CRS: WGS 84 / UTM zone 47N
# A tibble: 77 × 6
   nb        wt     province_en total_cases ADM1_PCODE                  geometry
 * &lt;nb&gt;      &lt;list&gt; &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;             &lt;MULTIPOLYGON [m]&gt;
 1 &lt;int [3]&gt; &lt;dbl&gt;  Amnat Char…       35435 TH37       (((1137720 1809629, 1137…
 2 &lt;int [4]&gt; &lt;dbl&gt;  Ang Thong         16168 TH15       (((643472.8 1636469, 643…
 3 &lt;int [6]&gt; &lt;dbl&gt;  Bangkok          286480 TH10       (((674339.8 1543300, 674…
 4 &lt;int [3]&gt; &lt;dbl&gt;  Bueng Kan         35287 TH38       (((965496 2045531, 96562…
 5 &lt;int [5]&gt; &lt;dbl&gt;  Buri Ram          57352 TH31       (((921217 1750212, 92121…
 6 &lt;int [8]&gt; &lt;dbl&gt;  Chachoengs…       53514 TH24       (((722656.1 1546054, 722…
 7 &lt;int [4]&gt; &lt;dbl&gt;  Chai Nat          15310 TH18       (((620165.4 1704256, 620…
 8 &lt;int [4]&gt; &lt;dbl&gt;  Chaiyaphum        64497 TH36       (((772997.4 1851276, 773…
 9 &lt;int [5]&gt; &lt;dbl&gt;  Chanthaburi       31473 TH22       (((853764.8 1360716, 853…
10 &lt;int [5]&gt; &lt;dbl&gt;  Chiang Mai       121812 TH50       (((554883.3 2226795, 555…
# ℹ 67 more rows</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>